import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";

// Initialize the Inter font with the "latin" subset
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        {/* Apply the Inter font to the body */}
        <body className={inter.className}>
          {/* Navbar component */}
          <Navbar />

          {/* Main content */}
          <div className="pt-20 min-h-screen flex flex-col">{children}</div>

          {/* Toaster component for notifications */}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}